version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: /bin/bash -c "sleep 7; python3 manage.py runserver -h 0.0.0.0 -p 8000 -r -d"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

