# Generated by Django 3.1.5 on 2021-01-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_page',
            field=models.BooleanField(default=False),
        ),
    ]
